# Generated by Django 4.1.2 on 2022-10-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Sugestão de Post',
                'verbose_name_plural': 'Sugestões de Posts',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='initials',
            field=models.CharField(default='  ', max_length=2, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/uploads', verbose_name='Imagem'),
        ),
    ]
